### PR TITLE
add height edit

### PR DESCRIPTION
**Pull request by mbouzi**
https://storjlabs.atlassian.net/secure/RapidBoard.jspa?rapidView=59&projectKey=USR&modal=detail&selectedIssue=USR-1279

### CODE REVIEW

**Review by boshevski — CHANGES_REQUESTED** [review]
Hey Malcolm, still seeing the image being cut-off on 4k displays. You can fix it by changing the section "container-fluid" to "container". 
4k

**Comment by mbouzi** [comment]
@boshevski decided to add more height because changing that class took it took far from the original design. Let me know if you have any other ideas 
Screen Shot 2020-10-29 at 9 28 54 AM
Screen Shot 2020-10-29 at 9 28 26 AM

**Comment by boshevski** [comment]
The image is still being cut-off, and the text is so wide, check out how it looks: 
4k-careers

**Review by boshevski — APPROVED** [review]
Looks good now

**Pull request merged**
