### PR TITLE
remove anonymous id push

### PR DESCRIPTION
**Pull request by mbouzi**
- remove anonymous id call
- email being push in "/layouts/partials/sign-up-node-operator-email/form.html"

### CODE REVIEW

**Review by mtchbss — CHANGES_REQUESTED** [review]
I see you totally removed the identify() call.  But, if I am not mistaken, I think we still need to call identify() in this scenario, but with the email from the form, which I think is inputs.email (_or whatever its DOM id is_), ala...

```analytics.identify(inputs.email.value);```

**Comment by mbouzi** [comment]
> I see you totally removed the identify() call. But, if I am not mistaken, I think we still need to call identify() in this scenario, but with the email from the form, which I think is inputs.email (_or whatever its DOM id is_), ala...
> 
> `analytics.identify(inputs.email.value);`

alluded to this in the PR description, the email is not actually being captured on this page. Its on the step afterward in this multistep sign up process @mtchbss

**Comment by mtchbss** [comment]
Ok on removing the identify(), but then why leave the 2 subsequent analytics.track() calls?  If this action cannot be tied to the user, I believe Aria is ok with omitting it entirely from their event tracking.  Did I make that up? Or did she not say that?

**Review by mtchbss — CHANGES_REQUESTED** [review]
Ok on removing the identify(), but then why leave the 2 subsequent analytics.track() calls? (line 54, line 62)  If this action cannot be tied to the user, I believe Aria is ok with omitting it entirely from their event tracking. Did I make that up? Or did she not say that?

**Comment by mbouzi** [comment]
> Ok on removing the identify(), but then why leave the 2 subsequent analytics.track() calls? (line 54, line 62) If this action cannot be tied to the user, I believe Aria is ok with omitting it entirely from their event tracking. Did I make that up? Or did she not say that?

thats a good point. I think on this step the user is just checking off boxes, all of the boxes need to be checked for them to move forward with the process. Im guess in this part there's nothing to necessarily track to a specific user, but we're tracking that this page has been interacted with in general @mtchbss

**Comment by mbouzi** [comment]
@mtchbss so in one call a successful completion is being tracked, and with another its tracking when a user did not successfully complete the form

**Review by mtchbss — CHANGES_REQUESTED** [review]
I verified with Aria. She wants those analytics.track() calls removed as well, because at this point, without an email to start the identify() with, the .track() event is not significant to the growth team.

**Comment by mbouzi** [comment]
> I verified with Aria. She wants those analytics.track() calls removed as well, because at this point, without an email to start the identify() with, the .track() event is not significant to the growth team.

sounds good that makes sense, just made the change! @mtchbss

**Review by mtchbss — APPROVED** [review]

**Pull request merged**
