### PR TITLE
Update social and event sections

### PR DESCRIPTION
**Pull request by barbaraliau**
Add StartUp Temple event image and move to new 'Our Next Event' section for prominence.

### CODE REVIEW

**Review by dylanlott — APPROVED** [review]
LGTM

**Comment by barbaraliau** [comment]
Also updates sale details as per JQ

**Comment by prestwich** [comment]
LGTM as well. Verified on PC and iOS.

**Comment by super3** [comment]
@barbaraliau I noticed that the link([https://storj.io/HackTemple](https://storj.io/HackTemple)) goes to a 404 page.

**Pull request merged**
