### PR TITLE
Update the whitepaper page

### PR DESCRIPTION
**Pull request by boshevski**

### CODE REVIEW

**Review by mbouzi — CHANGES_REQUESTED** [review]
This looks good! just a couple of things to look into:
- might want to change the logo the the new version
- the background looks different from what's on the site currently, not sure if that was on purpose or not
Screen Shot 2020-04-03 at 10 15 12 AM
Screen Shot 2020-04-03 at 10 14 55 AM

**Comment by boshevski** [comment]
The logo is the new version, the same used in the storage node operator page and the community page. The background is changed to reflect the new design of the pages, using a gradient like on the storage node operator page.

**Comment by mbouzi** [comment]
> The logo is the new version, the same used in the storage node operator page and the community page. The background is changed to reflect the new design of the pages, using a gradient like on the storage node operator page.

would the logo being used in the homepage not apply to those pages? Not sure if that was just for the homepage or if it should be used across all pages

**Comment by boshevski** [comment]
The logo is being updated across the website, along with the refactoring of the navigation everywhere too. We can merge this now.

**Pull request merged**
